### ISSUE TITLE
Integration tests occasionally failing

### ISSUE THREAD

**Issue by robward-scisys** [robward-scisys/sldeditor#11]
Getting the following happening when travis runs the integration tests:

java.lang.NullPointerException: null
	at javax.swing.tree.DefaultTreeSelectionModel.resetRowSelection(DefaultTreeSelectionModel.java:774)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:291)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:188)
	at javax.swing.JTree.setSelectionPath(JTree.java:1633)
	at com.sldeditor.datasource.extension.filesystem.node.FileSystemNodeManager.getTreePath(FileSystemNodeManager.java:161)
	at com.sldeditor.datasource.extension.filesystem.node.FileSystemNodeManager.showNodeInTree(FileSystemNodeManager.java:76)
	at com.sldeditor.extension.filesystem.FileSystemExtension.setFolder(FileSystemExtension.java:339)
	at com.sldeditor.extension.filesystem.FileSystemExtension.open(FileSystemExtension.java:440)
	at com.sldeditor.SLDEditor.openFile(SLDEditor.java:626)
	at com.sldeditor.test.SLDTestRunner.runTest(SLDTestRunner.java:248)

**Comment by robward-scisys** [comment]
Completed as part of pull request #12

**Comment by robward-scisys** [comment]
Typical it's started failing again

**Comment by robward-scisys** [comment]
Out of a sample of about 3 it seems to be working.

Pull request #13

**Comment by robward-scisys** [comment]
It's back again...

**Comment by robward-scisys** [comment]
It works fine on Windows 7, OSX and Ubuntu 16.04 (Unity).

Seems to be a problem with headless linux and xvfb.

**Comment by robward-scisys** [comment]
Seems to be working now
