### ISSUE TITLE
zombie labels

### ISSUE THREAD

**Issue by rghosh0** [robward-scisys/sldeditor#255]
Labels stay in view after being removed. The Symbol and SLD tabs show the TextSymbolizer as gone, but the labels are still stuck there in the Map tab.

Here's a video (you can skip to 0:40)
https://drive.google.com/file/d/0B9Kv4E5NP1kFbnNLMjBMZk1HNzg/view?usp=sharing

**Comment by robward-scisys** [comment]
The GeoTools symbol renderer caches all labels drawn. Added missing code to clear the label cache when the style changes on the map. Label cache already cleared on symbol renderer.

If you get the latest code the issue should be fixed.

**Comment by rghosh0** [comment]
Now labels don't seem to work in a case where they did work before.

https://drive.google.com/file/d/0B9Kv4E5NP1kFdDlMeTB4MFNWa3M/view?usp=sharing

The error in the terminal is:

> SEVERE: Could not find 'null' in the FeatureType (belfast_ireland_osm_amenities), available attributes are: [the_geom, id, osm_id, name, type]
> org.geotools.filter.IllegalFilterException: Could not find 'null' in the FeatureType (belfast_ireland_osm_amenities), available attributes are: [the_geom, id, osm_id, name, type]
>         at org.geotools.renderer.lite.StreamingRenderer.checkAttributeExistence(StreamingRenderer.java:2095)
>         at org.geotools.renderer.lite.StreamingRenderer.getFeatures(StreamingRenderer.java:2008)
>         at org.geotools.renderer.lite.StreamingRenderer.processStylers(StreamingRenderer.java:1913)
>         at org.geotools.renderer.lite.StreamingRenderer.paint(StreamingRenderer.java:826)
>         at org.geotools.swing.RenderingTask.call(RenderingTask.java:106)
>         at org.geotools.swing.RenderingTask.call(RenderingTask.java:41)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)

There may be some null values for the name attribute for some of the features. Not sure if that matters.

**Comment by robward-scisys** [comment]
Found the issue and fixed it.
Also noticed that the sample data that gets used when drawing the symbol had an empty string in the belfast_ireland_osm_amenities dataset.  By way of using some half sensible data the first feature in the dataset is used as example data. If the text label is configured to use a property it displays a value.  In this case it would have been empty.

If you do a git pull the issues should be resolved.

**Comment by rghosh0** [comment]
Hey, noticed another issue involving labels:  the settings don't seem to get saved. If you skip to 1:00  in this video, you'll see that I'm trying to get the font to change, but when I switch away from and back to the TextSymbolizer, it forgot my changes.

https://drive.google.com/file/d/0B9Kv4E5NP1kFNUMxbjhndUkwZWM/view?usp=sharing

**Comment by robward-scisys** [comment]
Discovered the problem, bit of a serious issue caused by the new text symbolizers being created with the same contents, initially empty label, default font etc.  When one of the text symbols was edited it updated the wrong text symbol internally causing the problem.  Raised issue #260 for this fix.

Also discovered if more than one rules have the same name then the wrong rule is rendered.  Raised issue #263 and fixed it.

If you pull latest source code the issues should now be resolved.

**Comment by rghosh0** [comment]
Thanks! Fixed.

**Comment by rghosh0** [comment]
The zombie labels thing seems to be back. Maybe different cause, not sure.

https://drive.google.com/file/d/0B9Kv4E5NP1kFczJCa1pvMTdfQ00/view?usp=sharing

**Comment by robward-scisys** [comment]
I think I've killed them off again.
